# Dejar un servidor nginx funcionando en un entorno

-   hosts: all

    gather_facts: False
    become: True
    
    vars: {}
       
    pre_tasks:
        -   name: Asegurarme de que la conexión ssh se establece
            include_role: 
                name: ssh-connection
            
        -   setup:
                gather_subset:
                  - '!all'
        -   include_tasks: "pretasks/main.yaml"
            
    tasks:
        -   include_tasks: "tasks/main.yaml"

    post_tasks:
        -   include_tasks: "posttasks/main.yaml"

    handlers:
        -   import_tasks: "handlers/main.yaml"
